#!/bin/bash
#
# port_purge 0.1
#
# This script scans the installed packages in macports and
# uninstalls them if they do not have any dependents and
# is not in the "world" file provided.
#
# syntax:
#     $ port_purge [WORLD_FILE]
#
# TODO: [OPTIONS] is used when executing port uninstall 
# [WORLD_FILE] is list of packages that should be excluded
#
# This code is in public domain.
#
# Author: Timothy Kim (timothykim@timothylive.net)
#


if [[ $# -gt 1 ]]
then
    echo "Usage: [WORLD_FILE]" 1>&2
#    echo "[OPTIONS] doesn't get parsed but gets passed directly to port uninstall command" 1>&2
    exit 128
fi

use_wf=0

if [[ $# -eq 1 ]]
then
    if [ -r $1 ]
    then
        world_file=$1
        use_wf=1
    else
        echo "Invalid world file, continuing without a world file."
    fi
fi

# TODO:First check if port is installed

run="y"

# Get the list of installed packages and filter
while [[ "$run" =~ [Yy] ]]
do
    echo "Searching for installed packages with no dependents..."
    INSTALLED_PACKAGES=`port installed | awk '{ print $1 }'`

    declare -i COUNT
    PACKAGES=()
    COUNT=0

    for package in $INSTALLED_PACKAGES
    do
        if [ "$package" != "The" ]; then
            if [ $use_wf -eq 1 ]; then
                P=`grep "$package" $world_file`
                if [ "$P" == "$package" ]; then
                    continue
                fi
            fi
            OUTPUT=`port dependents $package | grep "no dependents"`
            if [ "$OUTPUT" != "" ]; then
                echo "- $package"
                PACKAGES[$COUNT]=$package
                COUNT=$COUNT+1
            fi
        fi
    done

    if [ $COUNT -eq 0 ]; then
        echo "No packages found."
        exit 0
    fi

    echo "Found $COUNT packages."

    echo -n "> Would you like to uninstall found packages? (y/[n]) : "

    read x

    if [[ "$x" =~ [^yY] ]]; then
        exit 0
    fi

    if [[ $EUID -ne 0 ]]; then
        echo "Error: Uninstallation must be done as root" 1>&2
        exit 1
    fi

    for package in ${PACKAGES[@]}
    do
        port uninstall $package
    done

    echo -n "> Would you like to scan again? ([y]/n) : "

    read run
done
